credentials:
  usernames:
    Aziendabio:
      name: Admin SYD
      email: admin@sydbioedilizia.it
      password: $2b$12$q/.XND2U6mo5G5md6g27b.7vOzbCRapxd80SM6RML4SpfU.4sZGS6
cookie:
  expiry_days: 30
  key: 3399e934773ed00eb2a3f25bc32fc124f9f6b26f8de36600e69d4fce7f1c0085
  name: syd_admin_v2
