from typing import Literal
from langgraph.graph import END
from src.graph.state import AgentState
import logging

logger = logging.getLogger(__name__)

def route_step(state: AgentState) -> Literal["tools", "execution", END]:
    """
    Tier 2 Deterministic Router.
    
    Decides the next node based on the 'internal_plan' generated by the Reasoning Node.
    This replaces the implicit LLM routing.
    
    Logos:
    1. Check for Fail-Fast (Validation Failed) -> Error Handler (or Terminate)
    2. Action == 'call_tool' -> Tools Node
    3. Action == 'ask_user' -> Execution Node (Synthesis)
    4. Action == 'terminate' -> END
    """
    
    internal_plan = state.get("internal_plan", [])
    if not internal_plan:
        logger.warning("⚠️ No internal plan found. Defaulting to Execution Node.")
        return "execution"
        
    latest_step = internal_plan[-1]
    
    # 1. FAIL-FAST CHECK
    # Note: Pydantic validation failures in Reasoning Node already set specific flags or error states.
    # We check if the step indicates a termination or critical failure.
    if latest_step.get("action") == "terminate":
        logger.info("🛑 Routing: Terminate Signal received.")
        return END
        
    # 2. TOOL EXECUTION
    if latest_step.get("action") == "call_tool":
        tool_name = latest_step.get("tool_name")
        if tool_name:
            # CRITICAL FIX: We must route to 'execution' first to let the LLM 
            # actually GENERATE the structured tool call message based on the plan.
            # Direct routing to 'tools' would fail because the last message is not an AIMessage with tool_calls.
            logger.info(f"👉 Routing: Proceed to Execution Node to trigger tool: {tool_name}")
            return "execution"
        else:
            logger.warning("⚠️ Action is 'call_tool' but 'tool_name' is missing. Fallback to Execution.")
            return "execution"

    # 3. ASK USER / SYNTHESIS
    if latest_step.get("action") == "ask_user":
        logger.info("🗣️ Routing: Proceed to Execution Node for User Response.")
        return "execution"
        
    # Default Fallback
    return "execution"
