// Types for static image imports (`import photo from './photo.jpg'` → StaticImageData).
// next-env.d.ts already references these, but it is generated by `next dev`/`next build`
// and git-ignored, so a clean checkout — CI runs type-check before build — lacks it.
/// <reference types="next/image-types/global" />
